# CMake generated Testfile for 
# Source directory: /home/veins/src/artery/scenarios/artery
# Build directory: /home/veins/src/artery/scenarios/artery
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(example-inet "/home/veins/src/omnetpp/bin/opp_run_release" "-n" "/home/veins/src/artery/src/artery:/home/veins/src/artery/src/traci:/home/veins/src/artery/extern/veins/examples/veins:/home/veins/src/artery/extern/veins/src/veins:/home/veins/src/artery/extern/inet/src:/home/veins/src/artery/extern/inet/examples:/home/veins/src/artery/extern/inet/tutorials:/home/veins/src/artery/extern/inet/showcases" "-l" "/home/veins/src/artery/src/artery/envmod/libartery_envmod.so" "-l" "/home/veins/src/artery/src/artery/storyboard/libartery_storyboard.so" "-l" "/home/veins/src/artery/extern/inet/out/clang-release/src/libINET.so" "-l" "/home/veins/src/artery/extern/veins/out/clang-release/src/libveins.so" "-l" "/home/veins/src/artery/src/artery/libartery_core.so" "omnetpp.ini" "-uCmdenv" "-cinet" "--sim-time-limit=20s")
set_tests_properties(example-inet PROPERTIES  WORKING_DIRECTORY "/home/veins/src/artery/scenarios/artery")
add_test(example-security "/home/veins/src/omnetpp/bin/opp_run_release" "-n" "/home/veins/src/artery/src/artery:/home/veins/src/artery/src/traci:/home/veins/src/artery/extern/veins/examples/veins:/home/veins/src/artery/extern/veins/src/veins:/home/veins/src/artery/extern/inet/src:/home/veins/src/artery/extern/inet/examples:/home/veins/src/artery/extern/inet/tutorials:/home/veins/src/artery/extern/inet/showcases" "-l" "/home/veins/src/artery/src/artery/envmod/libartery_envmod.so" "-l" "/home/veins/src/artery/src/artery/storyboard/libartery_storyboard.so" "-l" "/home/veins/src/artery/extern/inet/out/clang-release/src/libINET.so" "-l" "/home/veins/src/artery/extern/veins/out/clang-release/src/libveins.so" "-l" "/home/veins/src/artery/src/artery/libartery_core.so" "omnetpp.ini" "-uCmdenv" "-cinet_security" "--sim-time-limit=20s")
set_tests_properties(example-security PROPERTIES  WORKING_DIRECTORY "/home/veins/src/artery/scenarios/artery")
add_test(example-inet-mixed-vehicles "/home/veins/src/omnetpp/bin/opp_run_release" "-n" "/home/veins/src/artery/src/artery:/home/veins/src/artery/src/traci:/home/veins/src/artery/extern/veins/examples/veins:/home/veins/src/artery/extern/veins/src/veins:/home/veins/src/artery/extern/inet/src:/home/veins/src/artery/extern/inet/examples:/home/veins/src/artery/extern/inet/tutorials:/home/veins/src/artery/extern/inet/showcases" "-l" "/home/veins/src/artery/src/artery/envmod/libartery_envmod.so" "-l" "/home/veins/src/artery/src/artery/storyboard/libartery_storyboard.so" "-l" "/home/veins/src/artery/extern/inet/out/clang-release/src/libINET.so" "-l" "/home/veins/src/artery/extern/veins/out/clang-release/src/libveins.so" "-l" "/home/veins/src/artery/src/artery/libartery_core.so" "omnetpp.ini" "-uCmdenv" "-cinet_multiple_vehicle_types" "--sim-time-limit=20s")
set_tests_properties(example-inet-mixed-vehicles PROPERTIES  WORKING_DIRECTORY "/home/veins/src/artery/scenarios/artery")
add_test(example-inet-rsu "/home/veins/src/omnetpp/bin/opp_run_release" "-n" "/home/veins/src/artery/src/artery:/home/veins/src/artery/src/traci:/home/veins/src/artery/extern/veins/examples/veins:/home/veins/src/artery/extern/veins/src/veins:/home/veins/src/artery/extern/inet/src:/home/veins/src/artery/extern/inet/examples:/home/veins/src/artery/extern/inet/tutorials:/home/veins/src/artery/extern/inet/showcases" "-l" "/home/veins/src/artery/src/artery/envmod/libartery_envmod.so" "-l" "/home/veins/src/artery/src/artery/storyboard/libartery_storyboard.so" "-l" "/home/veins/src/artery/extern/inet/out/clang-release/src/libINET.so" "-l" "/home/veins/src/artery/extern/veins/out/clang-release/src/libveins.so" "-l" "/home/veins/src/artery/src/artery/libartery_core.so" "omnetpp.ini" "-uCmdenv" "-cinet_rsu" "--sim-time-limit=20s")
set_tests_properties(example-inet-rsu PROPERTIES  WORKING_DIRECTORY "/home/veins/src/artery/scenarios/artery")
add_test(example-veins "/home/veins/src/omnetpp/bin/opp_run_release" "-n" "/home/veins/src/artery/src/artery:/home/veins/src/artery/src/traci:/home/veins/src/artery/extern/veins/examples/veins:/home/veins/src/artery/extern/veins/src/veins:/home/veins/src/artery/extern/inet/src:/home/veins/src/artery/extern/inet/examples:/home/veins/src/artery/extern/inet/tutorials:/home/veins/src/artery/extern/inet/showcases" "-l" "/home/veins/src/artery/src/artery/envmod/libartery_envmod.so" "-l" "/home/veins/src/artery/src/artery/storyboard/libartery_storyboard.so" "-l" "/home/veins/src/artery/extern/inet/out/clang-release/src/libINET.so" "-l" "/home/veins/src/artery/extern/veins/out/clang-release/src/libveins.so" "-l" "/home/veins/src/artery/src/artery/libartery_core.so" "omnetpp.ini" "-uCmdenv" "-cveins" "--sim-time-limit=20s")
set_tests_properties(example-veins PROPERTIES  WORKING_DIRECTORY "/home/veins/src/artery/scenarios/artery")
add_test(example-veins-rsu "/home/veins/src/omnetpp/bin/opp_run_release" "-n" "/home/veins/src/artery/src/artery:/home/veins/src/artery/src/traci:/home/veins/src/artery/extern/veins/examples/veins:/home/veins/src/artery/extern/veins/src/veins:/home/veins/src/artery/extern/inet/src:/home/veins/src/artery/extern/inet/examples:/home/veins/src/artery/extern/inet/tutorials:/home/veins/src/artery/extern/inet/showcases" "-l" "/home/veins/src/artery/src/artery/envmod/libartery_envmod.so" "-l" "/home/veins/src/artery/src/artery/storyboard/libartery_storyboard.so" "-l" "/home/veins/src/artery/extern/inet/out/clang-release/src/libINET.so" "-l" "/home/veins/src/artery/extern/veins/out/clang-release/src/libveins.so" "-l" "/home/veins/src/artery/src/artery/libartery_core.so" "omnetpp.ini" "-uCmdenv" "-cveins_rsu" "--sim-time-limit=20s")
set_tests_properties(example-veins-rsu PROPERTIES  WORKING_DIRECTORY "/home/veins/src/artery/scenarios/artery")
add_test(example-envmod "/home/veins/src/omnetpp/bin/opp_run_release" "-n" "/home/veins/src/artery/src/artery:/home/veins/src/artery/src/traci:/home/veins/src/artery/extern/veins/examples/veins:/home/veins/src/artery/extern/veins/src/veins:/home/veins/src/artery/extern/inet/src:/home/veins/src/artery/extern/inet/examples:/home/veins/src/artery/extern/inet/tutorials:/home/veins/src/artery/extern/inet/showcases" "-l" "/home/veins/src/artery/src/artery/envmod/libartery_envmod.so" "-l" "/home/veins/src/artery/src/artery/storyboard/libartery_storyboard.so" "-l" "/home/veins/src/artery/extern/inet/out/clang-release/src/libINET.so" "-l" "/home/veins/src/artery/extern/veins/out/clang-release/src/libveins.so" "-l" "/home/veins/src/artery/src/artery/libartery_core.so" "omnetpp.ini" "-uCmdenv" "-cenvmod" "--sim-time-limit=20s")
set_tests_properties(example-envmod PROPERTIES  WORKING_DIRECTORY "/home/veins/src/artery/scenarios/artery")
